name: Build Check

on:
  push:
    branches: [ "main" ]
    paths-ignore: [".github/**", "README.md"]
    
  pull_request:
    branches: [ "main" ]
    paths-ignore: [".github/**"]
  
  workflow_dispatch:
  
jobs:
  build_angular_project:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
            node-version: 16.18.0

      - uses: actions/checkout@v3
      
      - name: Install latest npm version
        run: npm install -g npm
        
      - name: Changing Directory
        run: pwd
        
      - name: Install dependencies
        run: ls
       
      - name: Build Project
        run: ng build
