name: Build Check

on:
  push:
    branches: [ "main" ]
    paths-ignore: [".github/**", "README.md"]
    
  pull_request:
    branches: [ "main" ]
    paths-ignore: [".github/**"]
  
  workflow_dispatch:
  
jobs:
  setup_env:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
            node-version: 16.18.0
            
      - name: Angular Github Actions
        uses: mayurrawte/github-angular-actions@v1.1.0

      - uses: actions/checkout@v3
      
      - name: Install latest npm version
        run: npm install -g npm
        
      - name: Building Project
        run: cd todo-web-app/ && npm i && ng build
        
      ##- name: Install dependencies
       # run: npm i
       
      #- name: Build Project
       # run: ng build
